In [1]:
import pandas as pd

In [3]:
df_w_songs_genres = pd.read_csv('../data_w_song_genres/data_w_song_genres.csv')

In [4]:
df_category = df_w_songs_genres[['artists','name']].copy()

In [16]:
def categorize_popularity(value):
    if value <= 25:
        return "FLOP"
    elif 25 < value <= 50:
        return "MID"
    elif 50 < value <= 80:
        return "MID-HIT"
    
    return "HIT"

def categorize_numeric_features(value):
    if value <= 0.5:
        return 'Low'
    else:
        return 'High'

def categorize_bool_features(value):
    if value == 1 or value == True:
        return 'Yes'
    else:
        return 'No'

def categorize_mode(value):
    if value == 1:
        return 'Major'
    else:
        return 'Minor'


def categorize_key(value):
    key_dict = {
        -1: "Unknown",
        0: "C",
        1: "C♯/D♭",
        2: "D",
        3: "D♯/E♭",
        4: "E",
        5: "F",
        6: "F♯/G♭",
        7: "G",
        8: "G♯/A♭",
        9: "A",
        10: "A♯/B♭",
        11: "B",
    }
    return key_dict[value]

def categorize_duration(value):
    duration_dict = {
        (0, 60000): "Very short",
        (60001, 120000): "Short",
        (120001, 300000): "Mid",
        (300001, 480000): "Large",
        (480000, float("inf")): "Very large"
    }
    
    for (low, high), category in duration_dict.items():
        if low <= value < high:
            return category

def categorize_tempo(value):
    tempo_dict = {
        (0, 20): "Sin Tempo",
        (20, 40): "Grave",
        (40, 60): "Lento",
        (60, 66): "Largo",
        (66, 70): "Larghetto",
        (70, 76): "Adagio",
        (76, 80): "Adagietto",
        (80, 108): "Andante",
        (108, 112): "Moderato",
        (112, 120): "Allegretto",
        (120, 168): "Allegro",
        (168, 176): "Vivace",
        (176, 200): "Presto",
        (200, float("inf")): "Prestissimo"
    }

    for (low, high), category in tempo_dict.items():
        if low <= value < high:
            return category
    
    return 

def categorize_year(value):
    decade = (value // 10) * 10
    if value < 2000:
        return f"{decade % 100}s"
    else:
        return f"{decade}s"

In [17]:
numeric_columns = [col for col in df_w_songs_genres.columns if col not in ["popularity","artists","duration_ms","id","key","mode","name","release_date","year","imputed_date","genres"]]

df_w_songs_genres["release_date"] = pd.to_datetime(df_w_songs_genres["release_date"])

In [18]:
for col in numeric_columns:
    df_category[col] = df_w_songs_genres[col].apply(categorize_numeric_features)

df_category['popularity'] = df_w_songs_genres['popularity'].apply(categorize_popularity).astype('category')

df_category['duration'] = df_w_songs_genres['duration_ms'].apply(categorize_duration).astype('category')

df_category["tempo"] = (
    df_w_songs_genres["tempo"].apply(categorize_tempo).astype("category")
)

df_category["key"] = df_w_songs_genres["key"].apply(categorize_key).astype("category")

df_category['explicit'] = df_w_songs_genres['explicit'].apply(categorize_bool_features).astype('category')

df_category["imputed_date"] = (
    df_w_songs_genres["imputed_date"].apply(categorize_bool_features).astype("category")
)

df_category["mode"] = (
    df_w_songs_genres["mode"].apply(categorize_mode).astype("category")
)

df_category["month"] = (
    df_w_songs_genres["release_date"].dt.month_name().astype("category")
)

df_category['year'] = df_w_songs_genres['year'].apply(categorize_year).astype('category')

In [19]:
df_w_songs_genres[df_w_songs_genres["name"] == "Happy New Years!! (Clear Vision)"]

,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,...,popularity,release_date,speechiness,tempo,valence,year,imputed_date,month,featuring,genres
120003,0.137,N.A.T.E. Jones,0.0,8042,0.279,1,334gn6CIPuCzq5laDm1m0Y,0.000122,10,0.342,...,0,2000-03-07,0.0,0.0,0.0,2020,False,1,False,[]

In [21]:
df_category

,artists,name,acousticness,danceability,energy,explicit,instrumentalness,liveness,loudness,speechiness,tempo,valence,month,featuring,popularity,duration,key,imputed_date,mode,year
0,Mamie Smith,Keep A Song In Your Soul,High,High,Low,No,Low,Low,Low,Low,Allegro,High,January,Low,FLOP,Mid,F,Yes,Minor,20s
1,Mamie Smith,Golfing Papa,High,High,Low,No,Low,High,Low,Low,Andante,High,January,Low,FLOP,Mid,C,Yes,Major,20s
2,Oscar Velazquez,True House Music - Xavier Santos & Carlos Gomi...,Low,High,High,No,High,Low,Low,Low,Allegro,Low,January,Low,FLOP,Large,D,No,Major,20s
3,Mixe,Xuniverxe,Low,High,High,Yes,Low,Low,Low,Low,Allegro,Low,January,Low,FLOP,Mid,A♯/B♭,No,Minor,20s
4,Mamie Smith & Her Jazz Hounds,Crazy Blues - 78rpm Version,High,Low,Low,No,High,Low,Low,Low,Andante,Low,October,Low,FLOP,Mid,F,Yes,Major,20s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132064,Alessia Cara,A Little More,High,Low,Low,No,Low,Low,Low,Low,Andante,Low,May,Low,FLOP,Mid,E,No,Major,2020s
132065,Alessia Cara,A Little More,High,Low,Low,No,Low,Low,Low,Low,Andante,Low,October,Low,FLOP,Mid,E,No,Major,2020s
132066,Alessia Cara,A Little More,High,Low,Low,No,Low,Low,Low,Low,Andante,Low,January,Low,FLOP,Mid,E,No,Major,2020s
132067,Alessia Cara,A Little More,High,Low,Low,No,Low,Low,Low,Low,Andante,Low,May,Low,FLOP,Mid,E,No,Major,2020s
132068,Taylor Swift,champagne problems,High,Low,Low,Yes,Low,Low,Low,Low,Vivace,Low,January,Low,MID-HIT,Mid,C,No,Major,2020s

In [22]:
df_category.to_csv('data_category.csv', index=False)